-- create sequence flight_sequence start with 1 increment by 1;
-- insert into Flight(id, travelOrderId, fromAirPort, toAirPort) values (nextval('flight_sequence'), 1, 'GRU', 'MCO');
-- insert into Flight(id, travelOrderId, fromAirPort, toAirPort) values (nextval('flight_sequence'), 1, 'GRU', 'JFK');
-- insert into Flight(id, travelOrderId, fromAirPort, toAirPort) values (nextval('flight_sequence'), 1, 'GRU', 'ATL');
-- insert into Flight(id, travelOrderId, fromAirPort, toAirPort) values (nextval('flight_sequence'), 1, 'GRU', 'MEX');